### ISSUE TITLE
no email about crash spikes received after the one for 2021-03-18

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/spikes#13]
The release-mgmt lists hasn't see `Spikes in signatures in nightly the YYYY-MM-DD` emails after the one for 2021-03-18.

@calixteman Looks like you are already investigating based on your commits after it broke.

cc @rvandermeulen @jcristau @pascalchevrel

**Comment by calixteman** [comment]
@Archaeopteryx thank you for reporting, it's fixed now.
You should have received an email few minutes ago.
