### ISSUE TITLE
merge signatures that are the same modulo address

### ISSUE THREAD

**Issue by jcristau** [mozilla/spikes#4]
There's a persistent crash with signature xul.dll@0x******* | _PR_NativeRunThread | pr_root", where the address changes each build.  It would be nice if we could avoid considering each of them as a new one (at least in this case where foo.dll@0xdeadbeef is not the whole signature).

**Comment by calixteman** [comment]
Fixed in commit: https://github.com/mozilla/spikes/commit/9d9b5a8c622ffcf7fd58c62224a1cdf46ea6849b
Memory addresses are replaced by a regexp and the # of crashes are merged.
