### ISSUE TITLE
Remove unactionable signatures from report

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla/spikes#5]
Some signatures such as:

IPCError-browser | ShutDownKill
EMPTY: no crashing thread identified; ERROR_NO_THREAD_LIST
EMPTY: no crashing thread identified; ERROR_NO_MINIDUMP_HEADER

Are signatures that are not actionable and probably shouldn't be included in the report when they spike. The ShutDownKill signature, for example, can have 33733 crashes in two days, and seems to be on the report quite a bit.

**Comment by calixteman** [comment]
Fixed in commit: https://github.com/mozilla/spikes/commit/e6c5dbc11eb040a74078590feff812d38fa34cda
If you want to add others signatures, please report an issue.
